# Test extracting pose from AprilTag detection result

In [1]:
import numpy
import math

In [2]:
poses = numpy.asarray([[0.8601, -0.1563, 0.4855, 0.2274],
       [0.0610, 0.9766, 0.2062, 0.1104],
       [-0.5064, -0.1477, 0.8496, 0.9514],
       [0.0000, 0.0000, 0.0000, 1.0000]])
poses

array([[ 0.8601, -0.1563,  0.4855,  0.2274],
       [ 0.061 ,  0.9766,  0.2062,  0.1104],
       [-0.5064, -0.1477,  0.8496,  0.9514],
       [ 0.    ,  0.    ,  0.    ,  1.    ]])

In [3]:
rmat = poses[:3, :3]
rmat

array([[ 0.8601, -0.1563,  0.4855],
       [ 0.061 ,  0.9766,  0.2062],
       [-0.5064, -0.1477,  0.8496]])

In [4]:
tvec = poses[:3, 3]
tvec

array([0.2274, 0.1104, 0.9514])

In [5]:
def quaternion_from_matrix(matrix):
    """Return quaternion from rotation matrix.

    >>> R = rotation_matrix(0.123, (1, 2, 3))
    >>> q = quaternion_from_matrix(R)
    >>> numpy.allclose(q, [0.0164262, 0.0328524, 0.0492786, 0.9981095])
    True

    """
    q = numpy.empty((4, ), dtype=numpy.float64)
    M = numpy.array(matrix, dtype=numpy.float64, copy=False)[:4, :4]
    t = numpy.trace(M)
    if t > M[3, 3]:
        q[3] = t
        q[2] = M[1, 0] - M[0, 1]
        q[1] = M[0, 2] - M[2, 0]
        q[0] = M[2, 1] - M[1, 2]
    else:
        i, j, k = 0, 1, 2
        if M[1, 1] > M[0, 0]:
            i, j, k = 1, 2, 0
        if M[2, 2] > M[i, i]:
            i, j, k = 2, 0, 1
        t = M[i, i] - (M[j, j] + M[k, k]) + M[3, 3]
        q[i] = t
        q[j] = M[i, j] + M[j, i]
        q[k] = M[k, i] + M[i, k]
        q[3] = M[k, j] - M[j, k]
    q *= 0.5 / math.sqrt(t * M[3, 3])
    return q

In [6]:
quat = quaternion_from_matrix(poses)
quat

array([-0.09216271,  0.2583108 ,  0.05658931,  0.95998698])

In [ ]:
R = tr.random_rotation_matrix()